services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=loftypractical
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      container_name: djangoservice
      volumes:
        - .:/djangoservice
      ports:
        - '8000:8000'
      depends_on:
        - postgres