# Generated by Django 4.1.3 on 2022-11-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incrementer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvalue',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
