# Generated by Django 4.1.3 on 2022-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incrementer', '0002_remove_keyvalue_id_alter_keyvalue_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
