# Generated by Django 4.1.3 on 2022-11-19 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('9ee19a3f-2a4b-4476-9efc-67a6abc30d1a'), primary_key=True, serialize=False)),
                ('dog_image', models.CharField(max_length=255)),
            ],
        ),
    ]
