# Generated by Django 4.1.3 on 2022-11-19 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
